### ISSUE TITLE
Export each note as separate html file?

### ISSUE THREAD

**Issue by khurshid-alam** [rosmanov/Tomboy2HTML#1]
A option to export each note as a separate html file would be great.

**Comment by rosmanov** [comment]
The tool had been written before the Tomboy team added "Export to HTML" plugin. Currently, Tomboy supports exporting all notes in separate files. So, probably, you don't even need this script, do you?

**Comment by khurshid-alam** [comment]
I have many notes. I don't want to export theme one by one.

**Comment by rosmanov** [comment]
@khurshid-alam There is a bulk export in the recent versions:
![screenshot_2016-06-20_09-13-35](https://cloud.githubusercontent.com/assets/608192/16181594/4c66ef2c-36c7-11e6-84e6-0bb741ab394b.png)
In my case this operation produced `All\ Notes\ HTML\ Export` directory with files per note:

```
Realpath C.html
Start Here.html
Using Links in Tomboy.html
```

**Comment by rosmanov** [comment]
Added `-m (--multiple)` option. You can use `-p (--prefix)` option to export them into some directory:

```
./tomboy2html.py -m -p /path/to/directory/
```

(note the trailing slash)

**Comment by khurshid-alam** [comment]
Thanks. That works.
